### PR TITLE
Update the error state for "username already exists"

### PR DESCRIPTION
**Pull request by bitfalt**
Solves #671 

- [x] Change the error message in Signup and Login
- [x] Add the button to Signup modal
- [ ] Add the button to Login modal

### CODE REVIEW

**Comment by bitfalt** [comment]
Hi! I'm trying to test the button I added to check if it displays correctly and then start modifying the styling according to the Figma. However, I'm getting some problems when trying to open the modal in `localhost:3002`.

I'm getting the following error:
image

From the error I see that it is trying to make a request to `localhost:8001/x/starknet/sepolia?paymaster=true`. However I don't have anything running in `localhost:8001`. I assume I need to run the local devnet, but I was just wondering if there is a specific configuration or something needed.

I followed all the instructions in the README regarding Frontend Development.

**Comment by clicksave** [comment]
cc @broody any guidance on the issue Daniel is running into?

**Comment by broody** [comment]
@bitfalt thanks for the PR! Sorry, but the way we're setup currently is this requires some of our backend services to be running locally. I don't think there is a good alternative rn.

Let me help u push this PR across tho, again thanks for trying to tackle this!

**Comment by bitfalt** [comment]
okay okay! Could I dm you on Telegram or Discord to have better communication? I might need some guidance regarding proper implementation. I already modified the messages, but I usually struggle with setting up frontend related stuff, so some proper guidance would be amazing! :D

**Comment by broody** [comment]
> okay okay! Could I dm you on Telegram or Discord to have better communication? I might need some guidance regarding proper implementation. I already modified the messages, but I usually struggle with setting up frontend related stuff, so some proper guidance would be amazing! :D

Yeah absolutely, drop by discord here https://discord.gg/cartridge

Or you can do me on telegram at @broody_eth

**Comment by tarrencev** [comment]
@bitfalt thanks for this contribution. unfortunately our plans have changed here and we have an alternate path we're working towards

**Pull request closed without merging**
